FROM ubuntu:22.04 

LABEL maintainer="jtn7@pdx.edu"

RUN apt-get update -y 
RUN apt-get install -y python3-pip 

COPY /hw2 /app 

WORKDIR /app 

RUN pip install -r requirements.txt 

ENTRYPOINT ["python3"]

CMD ["app.py"] 
